language: node_js
# See http://stackoverflow.com/questions/40208309/travis-ci-build-failing-on-android-app-unsupported-major-minor-version-52
jdk: oraclejdk8
node_js:
  - "6"
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c 'drop table if exists song;' -U postgres travis_ci_test
  - psql -c 'create table song(id integer PRIMARY KEY, artist char(40) NOT NULL, title varchar(40) NOT NULL, firstname varchar(40), name_index integer, name_length integer, date_inserted date, user_inserted varchar(40));' -U postgres travis_ci_test
  - psql -c "insert into song(id, artist, title, firstname, name_index, name_length, date_inserted, user_inserted) values(1, 'The Police', 'Roxanne', 'Roxanne', 0, 7, now(), 'Tester');" -U postgres travis_ci_test
addons:
  postgresql: "9.4"
env:
  NODE_ENV: "travis"
addons:
  sonarqube:
script:
# other script steps might be done before running the actual SonarQube analysis
  - sonar-scanner
