language: node_js
node_js:
  - "6"
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c 'create table song(id integer PRIMARY KEY, artist char(40) NOT NULL, title varchar(40) NOT NULL, firstname varchar(40), name_index integer, name_length integer, date_inserted date, user_inserted varchar(40));' -U postgres
  - psql -c "insert into song(id, artist, title, firstname, name_index, name_length, date_inserted, user_inserted) values(1, 'The Police', 'Roxanne', 'Roxanne', 0, 7, now(), 'Tester');" -U postgres
addons:
  postgresql: "9.4"
