language: node_js
node_js:
  - "6"
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c 'create table song (id integer) values (1);' -U postgres
addons:
  postgresql: "9.4"
